image: python:3.9

before_script:
  - pip install -U pip  # Upgrade pip
  - pip install -r requirements.txt  # Install necessary dependencies

pages:
  stage: deploy
  script:
    - python generate_homepage.py
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
